import './globals.css'

import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import AppProvider from '@/components/providers/app-provider'

const roboto = Roboto({
	variable: '--font-roboto',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${roboto.variable} antialiased`} suppressHydrationWarning>
				<AppProvider>
					{/* <SiteHeader /> */}
					<main role="main">{children}</main>
					{/* <SiteFooter /> */}
				</AppProvider>
			</body>
		</html>
	)
}
