// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type DevBlogPost = Collections['devPost']['schema']['_output']
export declare const devPost: DevBlogPost[]

export type BookRecap = Collections['bookRecap']['schema']['_output']
export declare const bookRecap: BookRecap[]

export type shortWriting = Collections['shortWriting']['schema']['_output']
export declare const shortWriting: shortWriting[]

export type ProjectPost = Collections['projectPost']['schema']['_output']
export declare const projectPost: ProjectPost[]

export type DocBlogPost = Collections['docPost']['schema']['_output']
export declare const docPost: DocBlogPost[]

export type retroPost = Collections['retroPost']['schema']['_output']
export declare const retroPost: retroPost[]
