// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type DevBlogPost = Collections['devPost']['schema']['_output']
export declare const devPost: DevBlogPost[]
